version: '3'
services:
  web-application:
    build: web-application
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
      - database-postgre
      - session
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=DucTreHouHa
      - MYSQL_DATABASE=bandFinderDatabase
  session:
    build: ./session
    ports:
      - "6379:6379"
  database-postgre:
    build: ./database-postgre
    environment:
      - POSTGRES_PASSWORD=DucTreHouHa
      - POSTGRES_USER=root
      - POSTGRES_DB=postDatabase
    ports:
      - "5432:5432"
  single-page-application:
    build: ./single-page-application
    ports:
      - "3030:3030"
    volumes:
      - "./single-page-application/src:/single-page-application/src"
    depends_on:
      - web-application